name: Pipeline Docker
on:
  push:
    branches:
      - main
  jobs:
    docker:
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Criar imagem
        run: docker build -t meu-site .

      - name: Executar container
        run: docker run -d -p 8080:80 --name site meu-site
        
      - name: Verificar container
        run: docker ps